services:
  xray:
    image: teddysun/xray
    container_name: xray-core
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./xray_config.json:/etc/xray/config.json:ro
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.core.rmem_max=26214400
      - net.core.wmem_max=26214400

  amnezia-wg:
    image: ghcr.io/linuxserver/wireguard:latest
    container_name: amnezia-wg
    restart: unless-stopped
    volumes:
      - ./amnezia_wg.conf:/config/wg0.conf:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
